language: python

python:
  - "3.5"
  - "3.6"

services:
  - redis-server

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - /bin/true

branches:
  only:
    - master

notifications:
  email: false
